name: pr-labels

on:
  push:
    branches:
      - master

jobs:
  is-properly-labeled:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2

      - name: Install requests
        run: pip3 install requests==2.26

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process commit and find merger responsible for labeling
        id: commit
        env:
          SHA1: ${{ github.sha }}
        run: |
          MERGER=$(python .github/scripts/process_commit.py "${SHA1}")
          echo "::set-output name=merger::${MERGER}"

      - name: Ping merger responsible for labeling if necessary
        if: ${{ steps.commit.outputs.merger != '' }}
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Hey ${{ steps.commit.outputs.merger }}!

            You merged this PR, but no release notes category and topic labels were added. The list of valid release and topic labels is available at https://github.com/pytorch/pytorch/labels?q=release and https://github.com/pytorch/pytorch/blob/master/.github/scripts/process_commit.py
